import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { Header } from "@/components/header/Header";
import { About } from "@/components/about/About";
import { Projects } from "@/components/projects/Projects";
import { Skills } from "@/components/skills/Skills";
import { Path } from "@/components/path/Path";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Portfolio Web Development</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<About />
			<Skills />
			<Path />
			<Projects />
		</>
	);
}
