import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import { projectList } from "@/data/projects";
import Image from "next/image";

import styles from "@/styles/projects.module.scss";
import { HeaderPages } from "@/components/header/HeaderPages";

import dart from "../../../public/img/dart11.png";

const inter = Inter({ subsets: ["latin"] });

export default function Project({ project }) {
	const {
		name,
		ref,
		github,
		description,
		technologies,
		roleOnTheProject,
		img,
	} = project;
	return (
		<>
			<Head>
				<title>Portfolio Web Development</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeaderPages />
			<section className={`section ${styles.section}`}>
				<div className={`container ${styles.container}`}>
					<h1 className={styles.title}>{name}</h1>

					<div className={styles.linkList}>
						<Link href={ref} target="_blank">
							Site
						</Link>
						<Link href={github} target="_blank">
							GitHub
						</Link>
					</div>
					<p className={styles.description}>{description}</p>
					<p>
						<b>The Technology Stack: </b>
						<span>{technologies}</span>{" "}
					</p>
					<p>
						<b>Project Role/Activity:</b>{" "}
						<span>{roleOnTheProject}</span>{" "}
					</p>
					<Image alt="progect" src={img} width={260} height={130} />
				</div>
				<div className={styles.imgBox}>
					<Image src={dart} alt="dragon" width="200" height="200" />
				</div>
			</section>
		</>
	);
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps({ params }) {
	// console.log(context);
	const result = projectList.find((el) => el.path === params.path);

	return {
		// Passed to the page component as props
		props: { project: result },
	};
}

export async function getStaticPaths() {
	return {
		paths: projectList.map(({ path }) => ({ params: { path } })),
		fallback: false, // can also be true or 'blocking'
	};
}
