import Head from "next/head";
// import Image from "next/image";
import { Inter } from "@next/font/google";
import { About } from "@/components/about/About";
import { Projects } from "@/components/projects/Projects";
import Link from "next/link";
import { projectList } from "@/data/projects";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Project({ project }) {
	const {
		name,
		ref,
		github,
		description,
		technologies,
		roleOnTheProject,
		img,
	} = project;
	return (
		<>
			<Head>
				<title>Portfolio Web Development</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>{name}</h1>
			<Link href={ref}>Site</Link>
			<Link href={github}>GitHub</Link>
			<p>{description}</p>
			<p>{technologies}</p>
			<p>Project Role/Activity: {roleOnTheProject}</p>
			<Image alt="progect" src={img} width={600} height={300} />
		</>
	);
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps({ params }) {
	// console.log(context);
	const result = projectList.find((el) => el.path === params.path);

	return {
		// Passed to the page component as props
		props: { project: result },
	};
}

export async function getStaticPaths() {
	return {
		paths: projectList.map(({ path }) => ({ params: { path } })),
		fallback: false, // can also be true or 'blocking'
	};
}
